### ISSUE TITLE
System.Runtime, Version=4.2.1.0

### ISSUE THREAD

**Issue by azamatz** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#108]
Hi!
I have a class library on netstandart 2.1 and add you package last version 3.1.0 but show error: 

Error	CS1705	Assembly 'Askmethat.Aspnet.JsonLocalizer' with identity 'Askmethat.Aspnet.JsonLocalizer, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'_

Last version 3.1.0 does support netstandart 2.1? Where info about this? 
Thanks.

**Comment by AlexTeixeira** [comment]
Hi,

Should support netstandard 2.1. I have any issue from my side with a fresh project. 
Can you share some code or a project ?
