### ISSUE TITLE
Error on binding models for error message using data annotation

### ISSUE THREAD

**Issue by matesols** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#113]
When I try to bind model for error message, it gives the following error

An unhandled exception occurred while processing the request.
JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Concurrent.ConcurrentDictionary`2[System.String,Askmethat.Aspnet.JsonLocalizer.Format.JsonLocalizationFormat]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)

![image](https://user-images.githubusercontent.com/56125800/115820986-590c9080-a41b-11eb-953b-ad2c38211640.png)

**Comment by AlexTeixeira** [comment]
Hi,

Can you share a sample of your JSON File and the plugin configuration ?
