### ISSUE TITLE
Drop support for .net core 3.1 and remove newtonsoft.json dependency

### ISSUE THREAD

**Issue by ErikApption** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#123]
I'd suggest dropping support for .net core 3.1 and move the code base to .net standard 2.1 +  .net 5/6. Also as part of this, I would suggest removing newtonsoft.json which is replaced by system.text.json
Should be a simple PR if this makes sense

**Comment by AlexTeixeira** [comment]
Yes could be a very good move. I already tried to move to system.text.json fiew months ago but I has an issue with dictionnary.

**Comment by ErikApption** [comment]
Have look https://github.com/AlexTeixeira/Askmethat-Aspnet-JsonLocalizer/pull/124

**Comment by AlexTeixeira** [comment]
Thanks for all the work you made.
