### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by strwase** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#13]
Hi, 

would it be possible to add an option to the configuration allowing me to set the encoding in which to read the json file?

I have noticed that after users change the translation file in notepad, save it without checking the encoding, end up setting it to ANSI or something.
After that, special characters are shown like an � after being localized.

so if you could add a config option allowing me to set the encoding in code, users can't ruin the localizations anymore by not saving in the proper encoding.

**Comment by AlexTeixeira** [comment]
Hi,

Thanks for using my package 👍 .

Yes it's totally possible. I will try to do it tomorrow, If the change does not break any test, i will update the current preview to version 2.

**Comment by strwase** [comment]
Great, that will help me avoid a lot of problems in the future :-)
