### ISSUE TITLE
GetAllStrings returns a wrong ResourceNotFound value for each string

### ISSUE THREAD

**Issue by lethek** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#18]
I believe the correct value for `LocalizedString.ResourceNotFound` should be `false` (when retrieved via `JsonStringLocalizer.GetAllStrings(includeParentCultures:false)`) and you probably set it to `true` there because Microsoft's [documentation for that property in versions prior to .NET Standard 2.0 was wrong](https://github.com/aspnet/Localization/commit/bc64eb9b997b48085b469a0f07144623297568d8#diff-fff51f00ea611636553355e7c818f96d).

**Comment by AlexTeixeira** [comment]
Version 1.1.4 correct this issue.
Thanks to your PR.
