### ISSUE TITLE
CultureInfo.CurrentCulture vs CultureInfo.CurrentUICulture

### ISSUE THREAD

**Issue by lethek** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#19]
Should the localizer be using CurrentUICulture instead of CurrentCulture by default?

From documentation I've read, it sounds like CurrentUICulture is meant to be used for resource-strings, and CurrentCulture is intended for formatting (numbers, dates, currency, etc.). Microsoft's own implementations of resource-string managers and StringLocalizers also rely on just CurrentUICulture.

However, I've also come across a couple comments that Windows can misrepresent a person's chosen culture with CurrentUICulture (back in 2012 with en-GB at least): see the Question Comments here https://stackoverflow.com/questions/329033/what-is-the-difference-between-currentculture-and-currentuiculture-properties-of#comment-11872860.  I'd think that might only be a concern with desktop applications though. Web-apps shouldn't be affected as there'd typically be a culture-provider selecting the relevant culture to use from a request/cookie etc.

**Comment by AlexTeixeira** [comment]
Hi,

I think you are right. And the library was created to support Net Standard And NetCore, so basically a user can use it for Windows App Or Xamarin App. 

Currently tests are using an instance of .NetCore WebApp application. So the "only thing" to do is to create tests that will use a WindowsApp And Xamarin App instance to have all scenario correctly tested.
