### ISSUE TITLE
Absolute Json Path

### ISSUE THREAD

**Issue by truccomarcos** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#23]
Is it possible to set the Resource path as an absolute address instead of one relative to the project folder?

**Comment by AlexTeixeira** [comment]
Hi,

Thanks for using my nuget package 👍 

It can be an evolution.
When I have some time, I will add an option to choose is the path is relative or absolute. 
By default, the value needs to be the relative one for regression purpose.

I will try to add the change as soon as possible.

**Comment by truccomarcos** [comment]
Thanks for answering! :smile: 

I tried implementing it but had some issues doing so. I'll keep trying and add a PR if i succeed.

**Comment by AlexTeixeira** [comment]
Hi,

I push a new version 1.1.6-preview1.
This new package have a new option : **IsAbsolutePath**, If you set this option to true, the **ResourcesPath** will not integrate any current project path.

Can you give some feedback, this feature is hard to test with integration tests, and I only did some basic tests .
