### ISSUE TITLE
Json file missing

### ISSUE THREAD

**Issue by 7atp** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#37]
Hi. I get this error after using this package with asp.net core 2.2
`DirectoryNotFoundException: Could not find a part of the path '\bin\Debug\netcoreapp2.2\json'.`
but after I copy manually JSON file to \bin\Debug\netcoreapp2.2\json the error gets fixed.

**Comment by 7atp** [comment]
Thanks @AlexTeixeira. it worked for me.

**Comment by AlexTeixeira** [comment]
@7atp Nice. I close the issue
