### ISSUE TITLE
Empty localizations are treated as non-existent

### ISSUE THREAD

**Issue by IOrlandoni** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#39]
Localizations consisting of an empty string should be treated as valid. Some languages might have prefixes/suffixes that others dont, for example.

**Comment by AlexTeixeira** [comment]
Hi, 

Thanks for your issue and your PR. 
I will try to merge the PR this week.

**Comment by IOrlandoni** [comment]
@AlexTeixeira Did you get a chance to review the merge?

**Comment by AlexTeixeira** [comment]
Hi,

I merged your PR. I need to fix the #38 and I will update the package to version 2.0.1, I think it will be available tomorrow.

**Comment by AlexTeixeira** [comment]
Fixed in 2.0.1
