### ISSUE TITLE
Culture not processed correctly

### ISSUE THREAD

**Issue by code-chris** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#46]
Hi,
I started using your nice library to overcome old resx structures ;). It is a .NET Core WebApplication where the translations should be returned for the current culture of the user. (Done with `stringLocalizer.WithCulture(user.Culture)...`.

But unfortunately I always receive the translation for the default culture (German in my case). If I read your code correctly, `WithCulture` has no effect and for the initialization of the Localizer the `CurrentUICulture` is used, which I can't use. So it is currently not possible for me to get things right...

Are there any plans to change the culture behavior (and only fallback to CurrentUICulture if nothing is set)? Even if not, it would be great to add a note to the docs to avoid needless research in future ;)

Thanks!

**Comment by AlexTeixeira** [comment]
Hi @code-chris,

Thanks for using the library :).

After some research, seems that WithCulture will be set Obsolete in version 3.0.0 ans removed in 4.0.0

Here some threads about this subject : 

https://github.com/aspnet/AspNetCore/issues/3324
https://github.com/aspnet/AspNetCore/issues/3289
https://github.com/aspnet/AspNetCore/issues/7756

In issues 7756 you have an example to overcome the WithCulture method.

I will add this info in the docs.

Thanks for noting this point.

**Comment by code-chris** [comment]
Hi @AlexTeixeira,
thanks for your quick reply. That's not the most elegant solution :wink: but it works :+1:.
Thanks for your research!
