### ISSUE TITLE
Change request culture and language

### ISSUE THREAD

**Issue by luftbornDeveloper** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#48]
I am trying to make my website bilingual, I set the culture with cookie like this.
                
               public IActionResult SetCulture(string id = "en")
		{
			var culture = id;
			Response.Cookies.Append(
			   CookieRequestCultureProvider.DefaultCookieName,
			   CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)), 
                                       new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
		   );
			var referer = Request.Headers["Referer"].ToString();
			referer = String.IsNullOrEmpty(referer) ? "/" : referer;
			var address = new Uri(referer);
			var path = address.AbsolutePath;
			return Redirect(path);
		}

but the language does not get changed unless I restart the application;
how can I change the language while the app is running.
Thanks.

**Comment by AlexTeixeira** [comment]
Hello,

This plugin is only a wrapper from the asp.net core globalization.
I never test to change the culture using cookie, but it should work.
I tested using HTTP Header and Query String.

You can have a look to official Microsoft documentation :

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#implement-a-strategy-to-select-the-languageculture-for-each-request

For the cookie implementation, you should read this part of the documentation : 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#cookierequestcultureprovider

Let me know if it still not working, I will investigate.

**Comment by luftbornDeveloper** [comment]
This is code in startup.cs
// configure  services
                        services.AddLocalization(options =>
			{
				options.ResourcesPath = "Localization";
			});

			services.AddSingleton<IStringLocalizerFactory, JsonStringLocalizerFactory>();



// configure app
           var supportedCultures = new List<CultureInfo> { new CultureInfo("en"), new CultureInfo("da") };
            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("da"),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures
            });

still not working, I have to restart application to get changes.
Also I tried to use accept-language Header but same result

**Comment by AlexTeixeira** [comment]
Hi,

You should also use  `app.UseRequestLocalization();` in Configure method.

Have you set this one too ?

**Comment by luftbornDeveloper** [comment]
yes, it is in the second code section in the previous comment.

**Comment by AlexTeixeira** [comment]
Ok, I will add an example in the **TestSample project** under test folder.

You also can have a look to this project, to check if the configuration are similar.

**Comment by AlexTeixeira** [comment]
Hello,

I found a good tutorial about localization.
You have a big part about _**Allowing users to select a culture**_

https://andrewlock.net/adding-localisation-to-an-asp-net-core-application/#allowing-users-to-select-a-culture

I also updated the test sample. You can have a look of a working template here : 

https://github.com/AlexTeixeira/Askmethat-Aspnet-JsonLocalizer/blob/master/test/Askmethat.Aspnet.JsonLocalizer.TestSample/

**Comment by bondo11** [comment]
@AlexTeixeira 
I see, You are right. It works in razor, bot not the dependency injection in the controller.

**Comment by AlexTeixeira** [comment]
@bondo11 good point, I didn't test in the controller. 
I will do some test and add feedback as soon as possible

**Comment by bondo11** [comment]
i think i found the issue:

if you set the:
```
			services.AddJsonLocalization(options =>
			{
                options.UseBaseName = false;
				options.ResourcesPath = "Localization";
			});
```
it doesn't work. You need to set the "UseBaseName" to true, to make it change language without restarting.

**Comment by bondo11** [comment]
So if you just use one or to translation files in the root of your translation folder, you need to restart the application before it changes language.

If you're translations is in septate files matching your views and cs files, it will work.

**Comment by AlexTeixeira** [comment]
I will try to have a look in the next days. Currently I have some other task to complete before taking this.

**Comment by bondo11** [comment]
No worries.. we found a workaround

**Comment by AlexTeixeira** [comment]
Good to know :). I keep the issue open to treat it later.
And thanks for all the information that you provided about this issue :)

**Comment by AlexTeixeira** [comment]
Same correction source
#49

**Comment by luftbornDeveloper** [comment]
great, now it is working on cshtml files when I use 
     @inject IViewLocalizer Localizer
but IViewLocalizer not working with controllers ".cs" files
and if I used 
	private readonly IStringLocalizer Localizer;
	public HomeController(IStringLocalizer _Localizer)
	{
		Localizer = _Localizer;
	}
then it needs to restart app again

**Comment by AlexTeixeira** [comment]
@luftbornDeveloper I fixed it in this pull request : 

https://github.com/AlexTeixeira/Askmethat-Aspnet-JsonLocalizer/commit/6dbc141921c8c353818b5034a282058144a23b20

It was an error from my side on initializing the injection.
I will try to fix the two waiting pull request and provide a new version

**Comment by luftbornDeveloper** [comment]
Thank you for following up, waiting the new release :)

**Comment by AlexTeixeira** [comment]
See version 2.1.0-preview-1

**Comment by luftbornDeveloper** [comment]
Thanks, it works now
