### ISSUE TITLE
Force Invalidation / Refresh of Memory Cache

### ISSUE THREAD

**Issue by JamesHill3** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#61]
I would love to see a way to invalidation/refresh the memory cache.

I'm allowing my users to update the localization.json file from an admin screen, and I need the changes to take effect immediately, not at the end of the expiration period.

**Comment by AlexTeixeira** [comment]
Hi @JamesHill3 ,

Thanks for using the plugin.
Your need is very interesting !! This is a good point to let the user manage the translation themselves without delay.

The question is, how to do it ?

I think the simplest way is to provide a public method to invalid the memory cache manually, what do you think about this idea ?

**Comment by JamesHill3** [comment]
Hi @AlexTeixeira 

Yes, I like your idea. Something similar to this would be beneficial, I think:

`
        /// <summary>
        /// Clear one or more cultures from MemoryCache so that they can be reloaded/refreshed.
        /// </summary>
        /// <param name="culturesToClearFromCache"></param>
        public void ClearMemCache(params CultureInfo[] culturesToClearFromCache)
        {
            // If one or more cultures are provided, clear only requested cultures, else clear all supported cultures.
            foreach (var cultureInfo in culturesToClearFromCache ??
                                         _localizationOptions.Value.SupportedCultureInfos.ToArray())
            {
                // May simply want to expose IMemoryCache.Remove() so it can be called here instead of _memCache.Set()
                _memCache.Set(GetCacheKey(cultureInfo), null, TimeSpan.Zero);
            }
        }`

Thoughts?

**Comment by AlexTeixeira** [comment]
Yes, I like this solution.

The more difficult part is to have some automated tests for this piece of code.

**Comment by JamesHill3** [comment]
Hey, @AlexTeixeira ! Any thing I can do to help move this along?

**Comment by AlexTeixeira** [comment]
Hey, @JamesHill3.

My previous weeks have been very busy. If you can provide a pull request with some changes, it can be great. 

If making test is too complicated, I will add them later.
I think I will have some time next week to have a look about this.

**Comment by AlexTeixeira** [comment]
Hi,

I add the method in the class and make some other changes.
The main issue is that I'm not able to access the methods from outside the project.

**Comment by AlexTeixeira** [comment]
Available on 2.2.0 preview 1. You can have a look

**Comment by JamesHill3** [comment]
@AlexTeixeira Sorry for the delay in responding. I'll definitely take look!

**Comment by JamesHill3** [comment]
Hi, @AlexTeixeira ! I've installed 2.2.o preview 1 and tested. The only issue I'm seeing (which was my fault), you've already corrected. This line...

```
// May simply want to expose IMemoryCache.Remove() so it can be called here instead of _memCache.Set()
_memCache.Set(GetCacheKey(cultureInfo), null, TimeSpan.Zero);
```

...is throwing the following error:

> The sliding expiration value must be positive. (Parameter 'SlidingExpiration')
> Actual value was 00:00:00.

Based on the latest code in the dev branch, it looks like you've already fixed that and replaced it with:

`_memCache.Remove(GetCacheKey(cultureInfo));`

Once that code makes it into the preview branch on Nuget, I'll test again.

Thanks for doing this! I'm sorry I didn't get to it myself, work has been crazy.

**Comment by AlexTeixeira** [comment]
Hi,

Damn, I fixed it but I did an incorrect handling before committing and forgot to add it again.
I will try to fixe that before end of week, work is crazy too for me ^^

**Comment by AlexTeixeira** [comment]
Should be ok on preview 3

**Comment by JamesHill3** [comment]
Hey, @AlexTeixeira 

I've tested preview 3. While I wasn't able to get it to work right away, I was able to track down the issue.

When passing in a relative path to the JSON, the localizer loads the files from the `bin` folder by default, thanks to the `GetJsonRelativePath()` method. So then, in order to get the `ClearMemCache()` to actually reload the JSON that has been modified from the modified file, and not the file copied into the `bin` folder, an absolute path is required.

I had to change my startup.cs code from this:

```
services.AddJsonLocalization(options =>
{
    options.CacheDuration = TimeSpan.FromMinutes(30);
    options.ResourcesPath = "LocalizationJson";
    options.FileEncoding = Encoding.UTF8;
    options.SupportedCultureInfos = _supportedCultures.ToHashSet();
}).AddScoped<LocalizationHelperService>();
```

To this:
```
services.AddJsonLocalization(options =>
{
    options.CacheDuration = TimeSpan.FromMinutes(30);
    options.ResourcesPath = Path.Combine(_hostEnvironment.ContentRootPath, "LocalizationJson");
    options.IsAbsolutePath = true;
    options.FileEncoding = Encoding.UTF8;
    options.SupportedCultureInfos = _supportedCultures.ToHashSet();
}).AddScoped<LocalizationHelperService>();
```

This also required that I inject `IHostEnvironment` into `Startup()`.

With those changes, I'm in business! I think the `ClearMemCache()` works just like it should. With that said, if the above changes aren't made part of the documentation, I think folks will have a hard time figuring out why the method appears not to work.

Thoughts?

**Comment by AlexTeixeira** [comment]
Hi,

Thanks for your feedback. 
Yes will add this detail in the documentation with your provided example. I think changing this way of working is not a good idea.

I will try to add more information about how the file are manage in a Wiki page.

Does that sound good to you?

**Comment by JamesHill3** [comment]
Sounds great!

I agree, changing the way the files are currently working would not be a good idea. I think the documentation change is enough. If you wanted to go the extra mile, it might be worth it to add comments to the method itself:

```
/// <summary>
/// In order to use this method, JsonLocalizationOptions.ResourcesPath & JsonLocalizationOptions.IsAbsolutePath = true must be set. For more information, see: [ref url to docs]
/// </summary>
/// <param name="culturesToClearFromCache">Specific cultures to clear from cache. If not provided, all cultures will be purged from cache.</param>
public void ClearMemCache(IEnumerable<CultureInfo> culturesToClearFromCache = null)
{
    // ...
}
```

Hey, great job on this. I'm using the localizer on a large business application that will be used in 3 countries in 3 languages. With this latest change, designated translator-users can update translations in real time.

**Comment by AlexTeixeira** [comment]
Ok. 

I will change the documentation and add comment  to the method. I will try to create the release for next week.

Thanks ! This is a very good point and I will use it too soon for an application that need dynamic translated product description :).

And thanks again for your time and help :)

**Comment by JamesHill3** [comment]
My pleasure!

**Comment by AlexTeixeira** [comment]
I create a wiki and update code :)
