### ISSUE TITLE
ViewModel DataAnnotation

### ISSUE THREAD

**Issue by wahmadel** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#62]
How to localize ViewModel DataAnnotations?

**Comment by AlexTeixeira** [comment]
Hi,

It works like the base localizer :

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#dataannotations-localization

**Comment by wahmadel** [comment]
Thanks, and it is a really good job.
