### ISSUE TITLE
"How to" Documentation 

### ISSUE THREAD

**Issue by arnoldsimha** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#74]
Is it possible to add different scenarios of how to use this library? for example data annotation, in views and controllers.
Thank you

**Comment by AlexTeixeira** [comment]
Hi @arnoldsimha ,

This library is just an extension of ASP.NET Core StringLocalizer. 

Follow the official documentation of Microsoft to know how to use Globalization : https://docs.microsoft.com/fr-fr/aspnet/core/fundamentals/localization?view=aspnetcore-2.2.

To use the JSON format from this library, just add the appropriate JSON files and the configuration that you want in your startup file like the example is the readme.

Also you have this project in this repo with simple example of how to use the library : https://github.com/AlexTeixeira/Askmethat-Aspnet-JsonLocalizer/tree/master/test/Askmethat.Aspnet.JsonLocalizer.TestSample

Hope this will help.

Alexandre.
