### ISSUE TITLE
Target nestandard instead of netcoreapp

### ISSUE THREAD

**Issue by tioduke** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#79]
Hi,

I've been using JsonLocalizer from some time now. For the time being, I had to stick to an older version because I am referencing it from a library that is compiled against nestandard2.0.

I understand that JsonLocalizer is meant to be used in Top Level projects (weapps), however bringing back netstandard as a dependency instead of netcoreapp could be great for cases like mine where the common face lifting is done in libraries instead of every single application.

Thank you in advance.

**Comment by AlexTeixeira** [comment]
Hi,

The migrations to netcore3.0 make some break changes.

Let me know if adding to the project a compatibility to netstandard2.0+ is enought for you ?

Here the dependencies to have something working in netstandard with a small set of changes in the project :

 ```
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' OR '$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.*"/>
        <PackageReference Include="Microsoft.Extensions.Localization" Version="3.*"/>
        <PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.*"/>
        <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.*"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.*"/>
    </ItemGroup>

```

**Comment by tioduke** [comment]
Yes, it is enough. Thank you.

**Comment by AlexTeixeira** [comment]
Ok. I will push this as soon as possible.
