### ISSUE TITLE
AddJsonLocalization for view localization

### ISSUE THREAD

**Issue by popraducj** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#8]
Can you please add a version for View localization?

**Comment by popraducj** [comment]
i just could not see the using.

**Comment by popraducj** [comment]
Actually I could use IStringLocalizer<string> in view and all worked well. Thank you for a great piece of code!

**Comment by AlexTeixeira** [comment]
@popraducj  Thanks for your feedback 😄 . 
If you have any idea for improvements or need more documentation, ask for it. 👍

**Comment by popraducj** [comment]
will it be hard to just return the string that is request in the following cases:
1 the key is not found
2 the language for the key is not found

This is kinda as the default behavior of IStringLocalizer from .netcore.  If you have time should not be a big change. If you want I can look into it and submit a pr.

**Comment by AlexTeixeira** [comment]
#9
