### ISSUE TITLE
Can't use JsonOptions

### ISSUE THREAD

**Issue by mohameds93** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#82]
i have installed the plugin in my project but i can't refrernce 
`using Askmethat.Aspnet.JsonLocalizer.JsonOptions;`
![askmethat](https://user-images.githubusercontent.com/10415486/83284443-f431c180-a1dc-11ea-992a-e7a157c385f1.PNG)

![oprions](https://user-images.githubusercontent.com/10415486/83284779-7d48f880-a1dd-11ea-9a55-30ecb0b8dbd0.PNG)

Please note that i downloaded the repo and i can see the refrence for this working.

**Comment by AlexTeixeira** [comment]
Hi,

This is strange, I have the last preview version and I don't have any issue with this import.

Can you give me more information about your project ?

**Comment by mohameds93** [comment]
I have .net core 3.1 webApi project which is the main and i have class library for localization.
I have added the plugin to the class library and followed the test sample project to get it work.
After that I had a problem with how Json file format are ,so i was trying to start using the i18n style
using the JsonOption and i get this issue.

**Comment by ItsMeSousuke** [comment]
@AlexTeixeira 
According to code downloaded of version 2.2.0 from github release JsonOptions are not included, are you going to create new release soon?

**Comment by AlexTeixeira** [comment]
Version 3.0.0 as non preview is also available now.

Sorry for delay in publishing the version 3.0.0.
Also I'm preparing a version 3.1.0 with #83  integration
