### ISSUE TITLE
Does the I18N model support hierarchical relationships?

### ISSUE THREAD

**Issue by penjay** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#83]
Does the I18N model support hierarchical relationships? 
If it is not supported, Put all keys in the same file?

eg：
localization.en-US.json
{
     "Page":{
           "Title": "title for page"
     }
}

localization.zh-CN.json
{
       "Page":{
            "Title": "标题"
       }
}

**Comment by AlexTeixeira** [comment]
Hi, 

For now, it does not support because the serialization model should be compatible between the I18n and the basic one.

But I think something can be created to have this king of JSON files if the call look like this :

`Localizer["Page:Title"]`

Let me knows if this idea is correct and I will try to implement it.

**Comment by penjay** [comment]
thank you for your reply.
Additional suggestions:
I think it should support different files like Basic, otherwise if there are tens of thousands of keys, the cache will take up a lot of resources. E.g:
Control which Json file is read by prefix:
SignUp.zh-CN.json [CacheKey="LocalizationBlob_SignUp.zh-CN"]
{
     "Title": "Register"
}
SignUp.en-US.json [.......................................... .................................en-US"]
{
       "Title": "Sign up"
}
SignIn...
SignIn...
Share.zh-CN.json [public key, for example: wrong format of mobile phone number]

transfer:
@Localizer["SignUp.Title"] You may need to control whether the prefix is ​​the file name or key through configuration parameters, for example:
prefix:'file' //key
Because if you use Basic mode, you need to write a lot of Values:{zh-CN:xxx,en-US:xxx}, and using I18N there are many third-party tools to manage language files, such as BabelEdit, so you get your update In the future, I changed it to I18N for the first time, but found the above deficiencies. If it can be updated to a new version, it will be perfect. Thank you.

![image](https://user-images.githubusercontent.com/23008915/84038560-ada94780-a9d2-11ea-91ab-8055efae9b9d.png)

**Comment by thefat32** [comment]
I implemented parsing for the mentioned kind of json:

localization.en-US.json
```json
{
   "Page":{
      "Title":"title for page"
   }
}
```
localization.zh-CN.json
```json
{
   "Page":{
      "Title":"标题"
   }
}
```

current `AddValueToLocalization` method in `LocalizationI18NModeGenerator.cs` should be something like this:

```cs
private void AddValueToLocalization(JsonLocalizationOptions options, string file, bool isParent)
        {
            var json = Newtonsoft.Json.JsonConvert.DeserializeObject(File.ReadAllText(file, options.FileEncoding));

            if (json == null)
            {
                return;
            }

            AddValues(json, null, isParent);
        }

        private void AddValues(dynamic input, string baseName, bool isParent)
        {
            // Json Object could either contain an array or an object or just values
            // For the field names, navigate to the root or the first element
            input = input.Root ?? input.First ?? input;

            if (input != null)
            {
                // check if the object is of type JObject. 
                // If yes, read the properties of that JObject
                if (input.GetType() == typeof(Newtonsoft.Json.Linq.JObject))
                {
                    // Create JObject from object
                    Newtonsoft.Json.Linq.JObject inputJson =
                        Newtonsoft.Json.Linq.JObject.FromObject(input);

                    // Read Properties
                    var properties = inputJson.Properties();

                    // Loop through all the properties of that JObject
                    foreach (var property in properties)
                    {
                        // Check if there are any sub-fields (nested)
                        if (property.Value.GetType() == typeof(Newtonsoft.Json.Linq.JObject))
                        {
                            // If yes, enter the recursive loop to extract sub-field names
                            var newBaseName = String.IsNullOrEmpty(baseName) ? property.Name : String.Format("{0}.{1}", baseName, property.Name);
                            AddValues(property.Value, newBaseName, isParent);
                        }
                        else if (property.Value.GetType() == typeof(Newtonsoft.Json.Linq.JArray))
                        {
                            throw new ArgumentException("Invalid i18n Json");
                        }
                        else
                        {
                            // If there are no sub-fields, the property name is the field name
                            AddOrUpdateLocalizedValue(
                                new KeyValuePair<string, string>(
                                String.IsNullOrEmpty(baseName) ? property.Name : String.Format("{0}.{1}", baseName, property.Name),
                                property.Value.ToString()
                                ),
                                isParent
                            );
                        }
                    }
                }
                else
                {
                    throw new ArgumentException("Invalid i18n Json");
                }
            }

        }
```

After doing this, access is:

```cs
Localizer["Page.Title"]
```

The json can have as nested objects as wanted, the leafs must be always strings, numbers or bools and it cannot contain arrays of course

**Comment by AlexTeixeira** [comment]
Hi,

I will integrate your changes this weekend and create a new version. I will notice you when the update is available :)

**Comment by AlexTeixeira** [comment]
Close. Create a new issue if needed
