### ISSUE TITLE
AbsolutPath Error

### ISSUE THREAD

**Issue by ghost** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#87]
Hi,

if you have your json files stored in an Assembly which (Copy files to Output Directory = true) is used by your maybe Blazor app, you have to set "AbsolutPath=False".
But in the .net core web app the filepath then will be like this:

...bin\\\Debug\\\netcoreapp3.1\\Locales\\\localisation.de-DE.json

Then you will get an error "Culture is not supported" because he has found o localization Name like '1\Locales…."

I have view your source Code and there is a Problem in your i18 Class:

  ` 
if (files.Any() && !isInvariantCulture)

            {

                foreach (var file in files)

                {

                    var splittedFiles = file.Split(Path.AltDirectorySeparatorChar);

                    var stringCulture = splittedFiles.Last().Split('.')[1];
                    var fileCulture = new CultureInfo(stringCulture);

                    var isParent =

                        fileCulture.Name.Equals(currentCulture.Parent.Name, StringComparison.OrdinalIgnoreCase);

                    if (fileCulture.Name.Equals(currentCulture.Name, StringComparison.OrdinalIgnoreCase) ||

                        isParent && fileCulture.Name != "json")

                    {

                        AddValueToLocalization(options, file, isParent);

                    }

                }

            }`

**Comment by AlexTeixeira** [comment]
Hi,

Some changes was made in this code. Please test in version 3.0.1 when it available

**Comment by AlexTeixeira** [comment]
No feedback about this issue. Closed
