### ISSUE TITLE
Support Blazor WebAssembly 

### ISSUE THREAD

**Issue by GoranHalvarsson** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#88]
Great repo!

Does it also support Blazor WebAssembly?

**Comment by AlexTeixeira** [comment]
Hi,

I use it with Blazor Server and it works fine.
I don't make any test with BlazorAssembly, but is ASP.NET Localiser is supported this repo should be supported too.

**Comment by AlexTeixeira** [comment]
Hi, I made some research about this and I did not able to make it work for now.

I will continue working on this to make it compatible with Blazor ASM.

**Comment by onepos-zaika** [comment]
Hello! Thank you for this amazing work.
We have been using JsonLocalizer in some of our projects smoothly. 
Now, we are trying to use it in Blazor ASM but received this error:

error BLAZORSDK1001: The project references the ASP.NET Core shared framework, which is not supported by Blazor WebAssembly apps.

We are able to contribute some work if this is something we can handle. Thank you.

**Comment by ErikApption** [comment]
See https://github.com/AlexTeixeira/Askmethat-Aspnet-JsonLocalizer/pull/122 for an initial prototype but there are serious limitations for loading files
