### ISSUE TITLE
Replace Newtonsoft.Json with System.Text.JSON 

### ISSUE THREAD

**Issue by GoranHalvarsson** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#89]
How about replacing Newtonsoft.Json with System.Text.JSON, any thoughts?

**Comment by AlexTeixeira** [comment]
Hi,

I will replace Newtonsoft with System.Text.JSON if it supports dictionary serialization. Last time I tries, Did not works

**Comment by AlexTeixeira** [comment]
Done on version 4.0.0
