### ISSUE TITLE
Blazor sample I18nTestSample doesn't work

### ISSUE THREAD

**Issue by ErikApption** [AlexTeixeira/Askmethat-Aspnet-JsonLocalizer#99]
IViewLocalizer ends up throwing an exception which according to https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1 is expected:

```
A limited set of ASP.NET Core's localization scenarios are currently supported:

IStringLocalizer and IStringLocalizer<T> are supported in Blazor apps.
IHtmlLocalizer, IViewLocalizer, and Data Annotations localization are ASP.NET Core MVC scenarios and not supported in Blazor apps. 
```
The demo app works by replacing IViewLocalizer with IStringLocalizer

**Comment by AlexTeixeira** [comment]
Hi,

Good to know, Is something missing for Blazor App and I have this issue a lot of time on my developping days ^^

**Comment by AlexTeixeira** [comment]
After looking to the **Common.cs**, can you explain the usage of this class ? Is it like the fallback csharp file in classic Microsoft localization ?

**Comment by ErikApption** [comment]
Oh, yes I created Common.cs to demonstrate how to have multiple json translation files if I recall correctly.

**Comment by AlexTeixeira** [comment]
Ok. I will create a 3.0.1 today :)

**Comment by AlexTeixeira** [comment]
Code mergerd.
